import type { Metadata } from "next";
import "./globals.css";
import NavBarGeneral from "@/components/nav-bar-general/NavBarGeneral"

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body>
         <NavBarGeneral/> 
        
        {children}

      </body>
    </html>
  );
}

